Models/ErrorViewModel.cs
namespace Project_management.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Project.cs
namespace Project_management.Models

{
    public class Project
    {
        public int Id  { get; set; }
        public string Name { get; set; }

        public ICollection<Ticket> Tickets { get; } = new List<Ticket>();
     

    }
}

Models/Ticket.cs
using System;

namespace Project_management.Models
{
    public class Ticket
    {
        public int Id { get; set; }
        public string Title { get; set; }

        public TaskStatus Status { get; set; } = TaskStatus.CREATED;
        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime ClosedAt { get; set; }

        public int ProjectId { get; set; }
        public Project Project { get; set; } = null!;


        public enum TaskStatus
        {
            CREATED,
            ASSIGNED,
            CLOSED
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Project_management.Models;

namespace Project_management.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;
using Project_management.Data;
using Project_management.Models;


namespace Project_management.Controllers
{
    public class ProjectsController : Controller
    {

        private ApplicationDbContext context;


        public ProjectsController(ApplicationDbContext ctx)
        {
            context = ctx;
        }

        public IActionResult Index()
        {
            return View(context.Projects.ToList());
        }

        [BindProperty]
        public Project? project { get; set; }

        public IActionResult Details(int id)
        {
            var project = context.Projects.FirstOrDefault(t => t.Id == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Add(Project project)
        {
            context.Projects.Add(project);
            context.SaveChanges();
            ViewBag.Count = context.Projects.Count();
            ViewBag.Projects = context.Projects.ToList();
            Console.Write("naiim");
            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            var project = context.Projects.FirstOrDefault(t => t.Id == id);
            if (project == null) return NotFound();
            return View(project);
        }

        public IActionResult Edit(Project project)
        {
            var oproject = context.Projects.FirstOrDefault(t => t.Id == project.Id);
            if (oproject == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                oproject.Name = project.Name;
                
                
                context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(oproject);
        }

         public IActionResult Delete(int id)
    {
        var project = context.Projects.FirstOrDefault(t => t.Id == id);
        if (project == null)
        {
            return NotFound();
        }
        return View(project);
    }


        [HttpPost]
    public IActionResult DeleteConfirm(int id)
    {
        var project = context.Projects.FirstOrDefault(t => t.Id == id);
        if (project == null)
        {
            return NotFound();
        }
        context.Projects.Remove(project);
        context.SaveChanges();
        return RedirectToAction("Index");
    }
}
}

Controllers/TicketsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Project_management.Data;
using Project_management.Models;


namespace Project_management.Controllers;

    [Authorize] 
    public class TicketsController : Controller
    {

        private ApplicationDbContext context;


        public TicketsController(ApplicationDbContext ctx)
        {
            context = ctx;
        }

        public IActionResult Index()
        {
            return View(context.Tickets.ToList());
        }

        [BindProperty]
        public Ticket? ticket { get; set; }

        public IActionResult Details(int id)
        {
            var ticket = context.Tickets.FirstOrDefault(t => t.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        public IActionResult Create()
        {
            var users = context.Users.ToList();
            Console.WriteLine(users.Count);
            foreach (var u in users)
            {
                Console.WriteLine(u.Email);
                
            }
            ViewBag.Projects = context.Projects.ToList();
            return View();
        }

        public IActionResult Add(Ticket ticket)
        {
            Console.WriteLine(ticket.ProjectId);
            context.Tickets.Add(ticket);
            context.SaveChanges();
            ViewBag.Count = context.Tickets.Count();
            ViewBag.Projects = context.Tickets.ToList();
            Console.Write("naiim");
            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            var ticket = context.Tickets.FirstOrDefault(t => t.Id == id);
            if (ticket == null) return NotFound();
            return View(ticket);
        }

        public IActionResult Edit(Ticket ticket)
        {
            var oticket = context.Tickets.FirstOrDefault(t => t.Id == ticket.Id);
            if (oticket == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                oticket.Title = ticket.Title;
                oticket.Status = ticket.Status;
                
                context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(oticket);
        }

         public IActionResult Delete(int id)
    {
        var ticket = context.Tickets.FirstOrDefault(t => t.Id == id);
        if (ticket == null)
        {
            return NotFound();
        }
        return View(ticket);
    }


        [HttpPost]
    public IActionResult DeleteConfirm(int id)
    {
        var ticket = context.Tickets.FirstOrDefault(t => t.Id == id);
        if (ticket == null)
        {
            return NotFound();
        }
        context.Tickets.Remove(ticket);
        context.SaveChanges();
        return RedirectToAction("Index");
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Project_management.Data;

namespace Project_management.Controllers;

public class UserController : Controller
{
    private ApplicationDbContext context;


    public UserController(ApplicationDbContext ctx)
    {
        context = ctx;
    }

    public IActionResult Index()
    {
        ViewBag.Users = context.Users.ToList();
        return View("Index", context.Users.ToList());
    }

    public IActionResult Create()
    {
        return View();
    }

}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About us";
}

<h1>About us</h1>
    <p1>this page contain information about the project</p1> 
   

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<style>
    body {
        background-image: url("https://d2fl3xywvvllvq.cloudfront.net/wp-content/uploads/2019/02/project_manager.jpg");
        background-repeat: no-repeat;
        background-size: cover;
    }
</style>

<div class="text-center">
    <h1 class="display-3">Welcome</h1>
   
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project_management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Project_management.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Project_management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Index">Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="Index">Tickets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Tickets/Create.cshtml
@model Project_management.Models.Ticket

<h1>Create New Ticket</h1>

<form asp-action="Add" method="post" class="form">
    <div class="mb-3">
        <label for="title" class="form-label">Title:</label>
        <input asp-for="@Model.Title" id="title" class="form-control" />
    </div>
    <div class="mb-3">
        <label for="projectId" class="form-label">Project:</label>
        <select id="projectId" name="projectId" class="form-select" asp-for="@Model.ProjectId">
            @foreach (var project in @ViewBag.Projects)
            {
                <option value="@project.Id">@project.Name</option>
            }
        </select>
    </div>
    <div class="mb-3">
        <label for="status" class="form-label">Status:</label>
        <select id="status" name="status" class="form-select" asp-for="@Model.Status">
            <option value="CREATED">Created</option>
            <option value="ON_GOING">On Going</option>
            <option value="CLOSED">Closed</option>
        </select>
    </div>
    <div>
        <button type="submit" class="btn btn-primary">Create</button>
    </div>
</form>

<hr />

<a href="@Url.Action("Index", "Tickets")" class="btn btn-secondary">Back to List</a>

Views/Tickets/Details.cshtml
@model Project_management.Models.Ticket

<h1>Ticket Details</h1>

<div>
    <p><strong>ID:</strong> @Model.Id</p>
    <p><strong>Title:</strong> @Model.Title</p>
    <p><strong>Status:</strong> @Model.Status</p>
    <p><strong>Created At:</strong> @Model.CreatedAt</p>
    
    @if (Model.Status == Project_management.Models.Ticket.TaskStatus.CLOSED)
    {
        <p><strong>Closed At:</strong> @Model.ClosedAt</p>
    }
</div>

<hr />

<a href="@Url.Action("Edit", "Tickets", new { id = Model.Id })">Edit</a> |
<a href="@Url.Action("Index", "Tickets")">Back to List</a>

Views/Tickets/Update.cshtml
@model Project_management.Models.Ticket

<h2>Edit Ticket</h2>

<form asp-action="Edit" asp-for="@Model.Id" >
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Title">Title</label>
        <input asp-for="@Model.Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

   

     <div class="mb-3">
        <label class="form-label">Status:</label>
        <select name="status" class="form-select" asp-for="@Model.Status">
            <option value="CREATED">Created</option>
            <option value="ON_GOING">On Going</option>
            <option value="CLOSED">Closed</option>
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Update</button>
</form>

Views/Tickets/delete.cshtml
@model Project_management.Models.Ticket

<h1>Delete Ticket</h1>

<div>
    <p><strong>ID:</strong> @Model.Id</p>
    <p><strong>Title:</strong> @Model.Title</p>
    <p><strong>Status:</strong> @Model.Status</p>
    <p><strong>Created At:</strong> @Model.CreatedAt</p>
    <p><strong>Closed At:</strong> @Model.ClosedAt</p>
</div>

<hr />

<form method="post" action="@Url.Action("DeleteConfirm", "Tickets", new { id = Model.Id })" onsubmit="return confirm('Are you sure you want to delete this project?');">
    <input type="hidden" name="id" value="@Model.Id" />
    <button type="submit">Delete</button>
    <a href="@Url.Action("Index", "Tickets")">Cancel</a>
</form>

Views/Tickets/index.cshtml
@{
    int? totalPages = (int)Math.Ceiling((double)Model.Count / 3);
    int activePage = 2;
    if (totalPages < activePage) activePage = totalPages.Value;
}

<h1>Ticket List</h1>

<div class="d-flex flex-wrap">
    @for (var i = 0; i < Model.Count; i++)
    {
        if (i % 3 == 0)
        {
            @:</div><div class="d-flex flex-wrap">
        }

        var ticket = Model[i];
        <div class="card m-2" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">@ticket.Title</h5>
                <p class="card-text">Status: @ticket.Status</p>
                <p class="card-text">Created At: @ticket.CreatedAt</p>
                <p class="card-text">Closed At: @ticket.ClosedAt</p>
                <a href="@Url.Action("Details", "Tickets", new { id = ticket.Id })" class="btn btn-primary">Details</a>
                <a href="@Url.Action("Update", "Tickets", new { id = ticket.Id })" class="btn btn-primary">Edit</a>
                <a href="@Url.Action("Delete", "Tickets", new { id = ticket.Id })" class="btn btn-primary">Delete</a>
            </div>
        </div>
    }
</div>

<hr />

<nav aria-label="...">
    <ul class="pagination">
        <li class="page-item @(activePage == 1 ? "disabled" : "")">
            <a class="page-link" href="#">Previous</a>
        </li>
        @for (var i = 0; i < totalPages; i++)
        {
            var pageNumber = i + 1;
            <li class="page-item @(pageNumber == activePage ? "active" : "")" aria-current="page">
                <a class="page-link" href="#">@pageNumber</a>
            </li>
        }
        <li class="page-item @(activePage == totalPages ? "disabled" : "")">
            <a class="page-link" href="#">Next</a>
        </li>
    </ul>
</nav>

<a href="@Url.Action("Create", "Tickets")" class="btn btn-primary">Create New Project</a>

Views/User/Create.cshtml
@model Microsoft.AspNetCore.Identity.IdentityUser;

<h1>Create New User</h1>

<form asp-action="Add" method="post" class="form">
    <div class="mb-3">
        <label for="title" class="form-label">Title:</label>
        <input asp-for="@Model.Email" id="title" class="form-control" />
    </div>


    <div>
        <button type="submit" class="btn btn-primary">Create</button>
    </div>
</form>

<hr />

<a href="@Url.Action("List", "Users")" class="btn btn-secondary">Back to List</a>

Views/User/index.cshtml
@{
    int? totalPages = (int)Math.Ceiling((double)Model.Count / 3);
    int activePage = 2;
}

<h1>Users List</h1>

<div class="d-flex flex-wrap">
    @foreach(var user in ViewBag.Users)
    {
        <div class="card m-2" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">@user.Email</h5>
                <p class="card-text">Status: @user.Id</p>
            </div>
        </div>
    }
</div>

<hr />

<nav aria-label="...">
    <ul class="pagination">
        <li class="page-item @(activePage == 1 ? "disabled" : "")">
            <a class="page-link" href="#">Previous</a>
        </li>
        @for (var i = 0; i < totalPages; i++)
        {
            var pageNumber = i + 1;
            <li class="page-item @(pageNumber == activePage ? "active" : "")" aria-current="page">
                <a class="page-link" href="#">@pageNumber</a>
            </li>
        }
        <li class="page-item @(activePage == totalPages ? "disabled" : "")">
            <a class="page-link" href="#">Next</a>
        </li>
    </ul>
</nav>

Views/projects/Create.cshtml
@model Project_management.Models.Project

<h1>Create New Project</h1>

<form asp-action="Add" method="post" class="form">
    <div class="mb-3">
        <label for="title" class="form-label">Name:</label>
        <input asp-for="@Model.Name" id="title" class="form-control" />
    </div>

    <div>
        <button type="submit" class="btn btn-primary">Create</button>
    </div>
</form>


<hr />

<a href="@Url.Action("Index", "projects")" class="btn btn-secondary">Back to List</a>

Views/projects/Details.cshtml
@model Project_management.Models.Ticket

<h1>Ticket Details</h1>

<div>
    <p><strong>ID:</strong> @Model.Id</p>
    <p><strong>Title:</strong> @Model.Title</p>
    <p><strong>Status:</strong> @Model.Status</p>
    <p><strong>Created At:</strong> @Model.CreatedAt</p>
    
    @if (Model.Status == Project_management.Models.Ticket.TaskStatus.CLOSED)
    {
        <p><strong>Closed At:</strong> @Model.ClosedAt</p>
    }
</div>

<hr />

<a href="@Url.Action("Edit", "Tickets", new { id = Model.Id })">Edit</a> |
<a href="@Url.Action("Index", "Tickets")">Back to List</a>

Views/projects/Update .cshtml
@model Project_management.Models.Ticket

<h2>Edit Ticket</h2>

<form asp-action="Edit" asp-for="@Model.Id" >
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Title">Title</label>
        <input asp-for="@Model.Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

   

     <div class="mb-3">
        <label class="form-label">Status:</label>
        <select name="status" class="form-select" asp-for="@Model.Status">
            <option value="CREATED">Created</option>
            <option value="ON_GOING">On Going</option>
            <option value="CLOSED">Closed</option>
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Update</button>
</form>

Views/projects/delete.cshtml
@model Project_management.Models.Project

<h1>Delete Project</h1>

<div>
    <p><strong>ID:</strong> @Model.Id</p>
    <p><strong>Nom:</strong> @Model.Name</p>
   
</div>

<hr />

<form method="post" action="@Url.Action("DeleteConfirm", "Projects", new { id = Model.Id })" onsubmit="return confirm('Are you sure you want to delete this project?');">
    <input type="hidden" name="id" value="@Model.Id" />
    <button type="submit">Delete</button>
    <a href="@Url.Action("Index", "Projects")">Cancel</a>
</form>

Views/projects/index.cshtml
@{
    int? totalPages = (int)Math.Ceiling((double)Model.Count / 3);
    int activePage = 2;
    if (totalPages < activePage) activePage = totalPages.Value;
}

<h1>project List</h1>

<div class="d-flex flex-wrap">
    @for (var i = 0; i < Model.Count; i++)
    {
        if (i % 3 == 0)
        {
            @:</div><div class="d-flex flex-wrap">
        }

       var project = Model[i];

        <div class="card m-2" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">@project.Name</h5>
             
                <a href="@Url.Action("Details", "Projects", new { id = project.Id })" class="btn btn-primary">Details</a>
                <a href="@Url.Action("Update", "Projects", new { id = project.Id })" class="btn btn-primary">Edit</a>
                <a href="@Url.Action("Delete", "Projects", new { id = project.Id })" class="btn btn-primary">Delete</a>
            </div>
        </div>
    }
</div>

<hr />

<nav aria-label="...">
    <ul class="pagination">
        <li class="page-item @(activePage == 1 ? "disabled" : "")">
            <a class="page-link" href="#">Previous</a>
        </li>
        @for (var i = 0; i < totalPages; i++)
        {
            var pageNumber = i + 1;
            <li class="page-item @(pageNumber == activePage ? "active" : "")" aria-current="page">
                <a class="page-link" href="#">@pageNumber</a>
            </li>
        }
        <li class="page-item @(activePage == totalPages ? "disabled" : "")">
            <a class="page-link" href="#">Next</a>
        </li>
    </ul>
</nav>

<a href="@Url.Action("Create", "Projects")" class="btn btn-primary">Create New project</a>